import { PublicShell } from '@/components/PublicShell';

export const metadata = { title: 'Terms · Rocket Sales Agent' };

export default function TermsPage() {
  return (
    <PublicShell>
      <article className="prose-invert max-w-3xl mx-auto px-6 py-12 text-white/80 text-sm leading-relaxed">
        <h1 className="text-2xl font-semibold tracking-tight text-white mb-2">Terms of Service</h1>
        <p className="text-white/50 text-xs mb-8">Last updated: 2026-05-05</p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">1. Acceptance</h2>
        <p>
          By creating a Rocket Sales Agent workspace you agree to these terms. If you are using
          Rocket on behalf of an organization, you represent that you are authorized to bind that
          organization to these terms.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">2. The service</h2>
        <p>
          Rocket Sales Agent (&quot;Rocket&quot;) is a sales-coaching tool that listens to live
          conference calls (currently Google Meet), generates suggestions grounded in knowledge
          documents you upload, and produces post-call recaps.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">3. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-5 space-y-1">
          <li>Use Rocket to record calls without the consent of all participants where required by law.</li>
          <li>Upload content you do not have the right to use.</li>
          <li>Reverse-engineer the service, attempt to circumvent rate limits, or probe for vulnerabilities outside an authorized program.</li>
          <li>Use Rocket for unlawful purposes or to harm minors.</li>
        </ul>
        <p className="mt-2">
          You are responsible for obtaining the consent required in your jurisdiction before
          recording or transcribing any meeting.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">4. Plans and billing</h2>
        <p>
          The Free plan is offered at no charge subject to the limits stated on the pricing page.
          Paid plans (when activated) are billed via Stripe. Refunds are handled case by case;
          contact{' '}
          <a className="underline" href="mailto:rajsuyash@gmail.com">
            rajsuyash@gmail.com
          </a>
          .
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">5. Your data</h2>
        <p>
          You retain all rights to the documents and content you upload. You grant Rocket a limited
          license to process that content solely to deliver the service to you. See our{' '}
          <a className="underline" href="/privacy">
            Privacy Policy
          </a>{' '}
          for details.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">6. AI output</h2>
        <p>
          Suggestions and recaps generated by Rocket are AI output and may contain errors. You are
          responsible for reviewing them before relying on them in a customer interaction.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">7. Termination</h2>
        <p>
          You may delete your workspace at any time from settings. We may suspend or terminate
          accounts that violate these terms.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">8. Disclaimers</h2>
        <p>
          The service is provided <strong>as is</strong>, without warranty of any kind. To the
          maximum extent permitted by law, Rocket disclaims all implied warranties.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">9. Limitation of liability</h2>
        <p>
          Rocket&apos;s aggregate liability under these terms is limited to the greater of $100 or
          the amount you paid Rocket in the 12 months preceding the claim.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">10. Changes</h2>
        <p>
          We may update these terms. Material changes will be communicated by email or in-product
          notice at least 14 days before they take effect.
        </p>

        <h2 className="text-lg font-semibold text-white mt-6 mb-2">11. Contact</h2>
        <p>
          <a className="underline" href="mailto:rajsuyash@gmail.com">
            rajsuyash@gmail.com
          </a>
        </p>
      </article>
    </PublicShell>
  );
}
